FROM buildpack-deps:22.04

# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

ENV PATH="/root/.cargo/bin:${PATH}"

# Install Node.js (required for caching target)
RUN apt-get update && \
    apt-get install -y nodejs npm \
