FROM --platform=linux/arm64 ubuntu:22.04

# Install build dependencies
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    curl

# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# Add Rust binaries to PATH
ENV PATH="/root/.cargo/bin:${PATH}"

# Install Node.js (required for caching target)
RUN apt-get update && \
    apt-get install -y nodejs npm
